version: '3.7'
services:
  api:
    command: ./scripts/ci-api.sh
  micro:
    command: ./scripts/ci-micro.sh
  ci:
    build:
      context: ${DOCKER_FRONT_ROOT:-.}
      target: ci
    networks:
      skeleton:
    depends_on:
      - micro
    volumes:
      - ${DOCKER_ROOT:-.}:/node:delegated
      - ci_node_modules:/node/node_modules
      - ci_dist:/node/dist
volumes:
  ci_node_modules:
  ci_dist:
