version: '3.8'
services:
  api:
    build:
      context: ${DOCKER_ROOT:-.}
      target: dev-api
    env_file:
      - ${DOCKER_ROOT:-.}/.env
    networks:
      skeleton:
        aliases:
          - api.local
    volumes:
      - ${DOCKER_ROOT:-.}:/node:delegated
      - api_node_modules:/node/node_modules
      - api_dist:/node/dist
    ports:
      - 3000:3000
  micro:
    build:
      context: ${DOCKER_ROOT:-.}
      target: dev-micro
    env_file:
      - ${DOCKER_ROOT:-.}/.env
    networks:
      skeleton:
        aliases:
          - micro.local
    volumes:
      - ${DOCKER_ROOT:-.}:/node:delegated
      - micro_node_modules:/node/node_modules
      - micro_dist:/node/dist
    ports:
      - 3001:3001
volumes:
  api_node_modules:
  api_dist:
  micro_node_modules:
  micro_dist:
networks:
  skeleton:
