version: '3.7'
services:
  ci:
    build:
      context: ${DOCKER_FRONT_ROOT:-.}
      target: ci
    networks:
      skeleton:
    depends_on:
      - micro
      - nats-1
      - nats-2
    volumes:
      - ${DOCKER_ROOT:-.}:/node:delegated
      - ci_node_modules:/node/node_modules
      - ci_dist:/node/dist
volumes:
  ci_node_modules:
  ci_dist:
