version: '3.7'
services:
  ci:
    build:
      context: ${DOCKER_FRONT_ROOT:-.}
      target: ci
    networks:
      skeleton:
    depends_on:
      - api
      - micro
    volumes:
      - ${DOCKER_ROOT:-.}:/node:delegated
      - ci_node_modules:/node/node_modules
volumes:
  ci_node_modules:
