version: '3.8'
services:
  api:
    build:
      context: ${DOCKER_ROOT:-.}
      target: development
    networks:
      skeleton:
    depends_on:
      - nats
      - micro
    env_file:
      - ${DOCKER_ROOT:-.}/.env
    command: ./scripts/api.sh
    volumes:
      - ${DOCKER_ROOT:-.}:/node:delegated
      - api_node_modules:/node/node_modules
    ports:
      - "3000:3000"
  micro:
    build:
      context: ${DOCKER_ROOT:-.}
      target: development
    networks:
      skeleton:
    depends_on:
      - nats
    env_file:
      - ${DOCKER_ROOT:-.}/.env
    command: ./scripts/micro.sh
    volumes:
      - ${DOCKER_ROOT:-.}:/node:delegated
      - micro_node_modules:/node/node_modules
  ci:
    build:
      context: ${DOCKER_FRONT_ROOT:-.}
      target: development
    networks:
      skeleton:
    depends_on:
      - api
      - micro
    env_file:
      - ${DOCKER_ROOT:-.}/.env
    environment:
      - NODE_ENV=$NODE_ENV
    command: ./scripts/ci.sh
    volumes:
      - ${DOCKER_ROOT:-.}:/node:delegated
      - ci_node_modules:/node/node_modules
  nats:
    image: nats
    ports:
      - "8222:8222"
    networks:
      skeleton:
  nats-1:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      skeleton:
    depends_on:
      - nats
  nats-2:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      skeleton:
    depends_on:
      - nats
volumes:
  api_node_modules:
  micro_node_modules:
  ci_node_modules:
networks:
  skeleton:
