on: workflow_dispatch
name: Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push images to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_API_REPOSITORY: skeleton/api
        ECR_MICRO_REPOSITORY: skeleton/micro
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_API_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_API_REPOSITORY:latest --target production-api .
        docker push $ECR_REGISTRY/$ECR_API_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_API_REPOSITORY:latest

        docker build -t $ECR_REGISTRY/$ECR_MICRO_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_MICRO_REPOSITORY:latest --target production-micro .
        docker push $ECR_REGISTRY/$ECR_MICRO_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_MICRO_REPOSITORY:latest
