on:
  workflow_dispatch:
    build:
      description: 'Build number'
      required: true
      default: 'latest'
name: Deploy
jobs:
  deploy:
    name: Deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Helm deploy to AWS
        uses: koslib/helm-eks-action@master
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_API_REPOSITORY: skeleton/api
          ECR_MICRO_REPOSITORY: skeleton/micro
          IMAGE_TAG: ${{ github.event.inputs.build }}
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          command: |
            helm upgrade skeleton --install --wait \
                --set api.image=$ECR_REGISTRY/$ECR_API_REPOSITORY:$IMAGE_TAG \
                --set micro.image=$ECR_REGISTRY/$ECR_MICRO_REPOSITORY:$IMAGE_TAG
